=== NiketaBihani/cms/src/test/resources/schema/hmhcms_com_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" 
  targetNamespace="http://www.hmhco.com/hmh-cms/com/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns:sem="http://marklogic.com/semantics" xmlns:com="http://www.hmhco.com/hmh-cms/com/1.0">
  <xs:import namespace="http://marklogic.com/semantics" schemaLocation="semantics.xsd"/>
  <xs:element name="object">
    <xs:annotation>
      <xs:documentation>Object instance (node)</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="com:properties"/>
        <xs:element ref="com:relationships" minOccurs="0"/>
        <xs:element ref="com:contains" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="versionNumber" use="required" type="xs:string"/>
      <xs:attribute name="versionURI" use="required" type="xs:anyURI"/>
      <xs:attribute name="workspaceURI" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="properties">
    <xs:annotation>
      <xs:documentation>Object properties</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="com:property"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="property">
    <xs:annotation>
      <xs:documentation>A property of the object</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="com:value"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="title" use="optional"/>
      <xs:attribute name="type" use="optional" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="relationships">
    <xs:annotation>
      <xs:documentation>Relationships of the object</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="com:relationship" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="com:correlations" minOccurs="0"/>
        <xs:element ref="sem:triples" minOccurs="0">
          <xs:annotation>
            <xs:documentation>We also store relationships as 'unmanaged' MarkLogic triples for future use. See https://docs.marklogic.com/guide/semantics/intro</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="contains">
    <xs:annotation>
      <xs:documentation>Other objects that the parent contains</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="com:object" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="relationship">
    <xs:annotation>
      <xs:documentation>A relationship of the object</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="com:value"/>
      </xs:sequence>
      <xs:attribute name="type" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="correlations">
    <xs:annotation>
      <xs:documentation>Correlations with standards. Note: they are actually relationships, but we need the additional information in the Standard element at least temporarily</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="com:standard" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="standard">
    <xs:annotation>
      <xs:documentation>A HMSI standard correlated with the object</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="com:customCode"/>
      </xs:sequence>
      <xs:attribute name="hmco" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="abGuid" use="optional" type="xs:string"/>
      <xs:attribute name="guid" use="optional" type="xs:string"/>
      <xs:attribute name="state" use="optional" type="xs:string"/>
      <xs:attribute name="source" use="optional" type="xs:string"/>
      <xs:attribute name="hierarchyId" use="optional" type="xs:string"/>
      <xs:attribute name="officialCode" use="optional" type="xs:string"/>
      <xs:attribute name="versionNumber" use="optional" type="xs:string"/>
      <xs:attribute name="versionName" use="optional" type="xs:string"/>
      <xs:attribute name="fromGrade" use="optional" type="xs:string"/>
      <xs:attribute name="toGrade" use="optional" type="xs:string"/>
      <xs:attribute name="standardText" use="optional" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="customCode" type="xs:string"/>
  <xs:element name="value" type="xs:string">
    <xs:annotation>
      <xs:documentation>Generic element for a (property) value representation</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>

=== NiketaBihani/cms/src/test/resources/schema/hmhcms_com_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Example of a valid COM XML file (stored in Alfresco on node version and also in ML) -->
<object type="hmh-cms:learningObject" 
    workspaceURI="workspace://SpacesStore/47fdf474-35dc-47ed-9a73-c290fc35952f" 
    versionURI="workspace://version2Store/ce88511e-dd21-4e93-a2ed-d6c41e0de0e1"
    versionNumber="1.1" name="Course Opener" 
    xmlns="http://www.hmhco.com/hmh-cms/com/1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:hmh-cms="http://www.hmhco.com/model/hmh-cms/1.0"
    xmlns:cm="http://www.alfresco.org/model/content/1.0"
    xsi:schemaLocation="http://www.hmhco.com/model/hmh-cms/1.0 hmhcms_com_schema.xsd">
    <properties>
        <!-- Not sure about the actual need for title and type here actually, but we include them anyway just in case -->
        <property name="cm:title" title="Display Title" type="d:text">
            <value>some title</value>
        </property>
        <property name="sys:node-uuid" title="CMSID" type="d:text">
            <value>47fdf474-35dc-47ed-9a73-c290fc35952f</value>
        </property>
        <property name="cm:description" title="Meaningful Description" type="d:text">
            <value>meaningful description</value>
        </property>
        <property name="cm:content" title="Content" type="d:text">
            <value>s3://-system-/contentstore/822e0bb6-ae46-4a85-bc34-33db4991ce12.bin</value>
        </property>
        <!-- NB MIME type is a "metaproperty", not a standalone in Alfresco -->
        <property name="cm:mimetype" title="MIME" type="d:text">
            <value>image/jpeg</value>
        </property>
        <property name="cm:modified" title="Modified" type="datetime">
            <value>2015-04-30T12:01:38+00:00</value>
        </property>
        <property name="hmh-cms:copyrightYear" title="Copyright Year" type="int">
            <value>2015</value>
        </property>
        <property name="hmh-cms:grade" title="Grade" type="d:text">
            <value>K</value>
            <value>1</value>
            <value>5</value>
        </property>
        <property name="cm:taggable" title="HMH Keywords" type="noderef">
            <value>tag 1</value>
            <value>tag 2</value>
        </property>
        <property name="cm:categories" title="Categories" type="noderef">
            <value>Category 1</value>
            <value>Category 2</value>
        </property>
    </properties>
    <relationships>
        <relationship type="hmh-cms:references">
            <value>workspace://version2Store/ce88511e-dd21-4e93-a2ed-d6c41e0de0e1</value>
            <value>workspace://SpacesStore/7b909bdb-a95a-418b-b17e-f246fc7ebfce</value>
        </relationship>
        <!-- note: correlated objects are not stored in ML, so that is for future use -->
        <relationship type="hmh-cms:correlation">
            <value>workspace://SpacesStore/01bccc29-9538-41ff-823e-c290fc35952f</value>
            <value>workspace://SpacesStore/7b909bdb-a95a-418b-b17e-f246fc7ebfce</value>
        </relationship>
        <correlations>
            <standard name="Math (2010) (79613598)" hmco="NT.CCSS.MTH.10" standardText="Math (2010) (79613598)" officialCode="1.1">
                <customCode>2015 National Go Math</customCode>
                <customCode>National Math (2010)</customCode>
            </standard>
        </correlations>
        <sem:triples
            xmlns:sem="http://marklogic.com/semantics">
            <sem:triple>
                <sem:subject>workspace://version2Store/ce88511e-dd21-4e93-a2ed-d6c41e0de0e1</sem:subject>
                <sem:predicate>http://www.hmhco.com/model/hmh-cms/1.0/references</sem:predicate>
                <sem:object>workspace://SpacesStore/798e3463-67c7-49cc-998b-4987f2e43d09</sem:object>
            </sem:triple>
            <sem:triple>
                <sem:subject>workspace://version2Store/ce88511e-dd21-4e93-a2ed-d6c41e0de0e1</sem:subject>
                <sem:predicate>http://www.hmhco.com/model/hmh-cms/1.0/correlation</sem:predicate>
                <sem:object>workspace://SpacesStore/7b909bdb-a95a-418b-b17e-f246fc7ebfce</sem:object>
            </sem:triple>
        </sem:triples>
    </relationships>
</object>

=== NiketaBihani/cms/src/test/resources/schema/hmhcms_csx_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Example of a valid COM Snapshot (CSX) XML file (stored in ML) -->
<object type="hmh-cms:productSet" 
    workspaceURI="workspace://SpacesStore/47fdf474-35dc-47ed-9a73-c290fc35952f" 
    versionURI="workspace://version2Store/ce88511e-dd21-4e93-a2ed-d6c41e0de0e1"
    versionNumber="1.1" name="Product Set" 
    xmlns="http://www.hmhco.com/hmh-cms/com/1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:hmh-cms="http://www.hmhco.com/model/hmh-cms/1.0"
    xmlns:cm="http://www.alfresco.org/model/content/1.0"
    xsi:schemaLocation="http://www.hmhco.com/model/hmh-cms/1.0 hmhcms_com_schema.xsd">
    <properties>
        <property name="cm:name" title="Name" type="d:text">
            <value>Product Set</value>
        </property>
        <property name="cm:title" title="Display Title" type="d:text">
            <value>PS title</value>
        </property>
        <property name="sys:node-uuid" title="CMSID" type="d:text">
            <value>47fdf474-35dc-47ed-9a73-c290fc35952f</value>
        </property>
        <property name="cm:modified" title="Modified" type="datetime">
            <value>2015-04-30T12:01:38+00:00</value>
        </property>
        <property name="cm:taggable" title="HMH Keywords" type="noderef">
            <value>tag 1</value>
            <value>tag 2</value>
        </property>
    </properties>
    <contains>
        <object type="hmh-cms:learningObject" 
            workspaceURI="workspace://SpacesStore/aa6bf282-a5d0-4fc9-a7a0-b1a9b40cd28e" 
            versionURI="workspace://version2Store/ce88511e-dd21-4e93-a2ed-d6c41e0de0e1"
            versionNumber="1.1" name="Learning Object">
            <properties>
                <property name="cm:name" title="Name" type="d:text">
                    <value>Learning Object</value>
                </property>
                <property name="cm:title" title="Display Title" type="d:text">
                    <value>PS title</value>
                </property>
                <property name="sys:node-uuid" title="CMSID" type="d:text">
                    <value>47fdf474-35dc-47ed-9a73-c290fc35952f</value>
                </property>
                <property name="cm:description" title="Meaningful Description" type="d:text">
                    <value>Some meaningful description</value>
                </property>
                <property name="cm:modified" title="Modified" type="datetime">
                    <value>2015-04-30T12:01:38+00:00</value>
                </property>
                <property name="cm:taggable" title="HMH Keywords" type="noderef">
                    <value>tag 1</value>
                    <value>tag 2</value>
                </property>
            </properties>
            <relationships>
                <correlations>
                    <standard name="Math (2010) (79613598)" hmco="NT.CCSS.MTH.10" standardText="Math (2010) (79613598)" officialCode="1.1">
                        <customCode>2015 National Go Math</customCode>
                        <customCode>National Math (2010)</customCode>
                    </standard>
                </correlations>
                <sem:triples
                    xmlns:sem="http://marklogic.com/semantics">
                    <sem:triple>
                        <sem:subject>workspace://version2Store/ce88511e-dd21-4e93-a2ed-d6c41e0de0e1</sem:subject>
                        <sem:predicate>http://www.hmhco.com/model/hmh-cms/1.0/references</sem:predicate>
                        <sem:object>workspace://SpacesStore/798e3463-67c7-49cc-998b-4987f2e43d09</sem:object>
                    </sem:triple>
                </sem:triples>
            </relationships>
        </object>
        <object type="hmh-cms:componentObject" 
            workspaceURI="workspace://SpacesStore/aa6bf282-a5d0-4fc9-a7a0-b1a9b40cd29e" 
            versionURI="workspace://version2Store/ce88511e-dd21-4e93-a2ed-d6c41e0de0e1"
            versionNumber="1.0" name="Component">
            <properties>
                <property name="cm:name" title="Name" type="d:text">
                    <value>Component</value>
                </property>
                <property name="cm:title" title="Display Title" type="d:text">
                    <value>Component</value>
                </property>
                <property name="sys:node-uuid" title="CMSID" type="d:text">
                    <value>47fdf474-35dc-47ed-9a73-c290fc35952f</value>
                </property>
                <property name="cm:modified" title="Modified" type="datetime">
                    <value>2015-04-30T12:01:38+00:00</value>
                </property>
            </properties>
        </object>
    </contains>
    <relationships>
        <relationship type="hmh-cms:correlation">
            <value>workspace://SpacesStore/01bccc29-9538-41ff-823e-c290fc35952f</value>
            <value>workspace://SpacesStore/7b909bdb-a95a-418b-b17e-f246fc7ebfce</value>
        </relationship>
        <correlations>
            <standard name="Math (2010) (79613598)" hmco="NT.CCSS.MTH.10" standardText="Math (2010) (79613598)" officialCode="1.1">
                <customCode>2015 National Go Math</customCode>
                <customCode>National Math (2010)</customCode>
            </standard>
        </correlations>
        <sem:triples
            xmlns:sem="http://marklogic.com/semantics">
            <sem:triple>
                <sem:subject>workspace://version2Store/ce88511e-dd21-4e93-a2ed-d6c41e0de0e1</sem:subject>
                <sem:predicate>http://www.hmhco.com/model/hmh-cms/1.0/correlation</sem:predicate>
                <sem:object>workspace://SpacesStore/7b909bdb-a95a-418b-b17e-f246fc7ebfce</sem:object>
            </sem:triple>
        </sem:triples>
    </relationships>
</object>
